version: "3.8"
services:
  number-service:
    build:
      context: ./number-service
      dockerfile: Dockerfile

  date-service:
    build:
      context: ./date-service
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - number-service
      - date-service
      - frontend
